apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - name: "ui"
    port: 5601
    targetPort: 5601
  selector:
    component: kibana
