apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hazelcast-ingress
spec:
  rules:
  - host: mancenter.ingress.sol.diamanti.com
    http:
      paths:
        - path: /hazelcast-mancenter
          backend:
            serviceName: demo-hazelcast-enterprise-mancenter
            servicePort: 8080
